server:
  port: 8081
spring:
  application:
    name: quickstart
my:
  mood:
    today: "Friday"
    content: "Today is a bad day"
    author: "cowhorse"
  feature:
    helloSwitch: true
    closeMsg: "该接口正在维护，10分钟后再来"