server:
  port: 8081
team:
  name: "team"
  leader: ${teacher.name}
  age: ${random.int(1,4)}
  phone: "18888888888"

teacher:
  name: "wby"
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 2794403372@qq.com #你的qq邮箱
    password: orvkhpjgpyuwdhcc #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Spring Boot #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
qrcode:
  content: "https://www.bilibili.com"